CRITICAL:root:{'date': datetime.datetime(2017, 10, 2, 17, 35, 53, 434366), 'type': 'CRITICAL', 'info': 'Error en la url', 'error': '!! Traceback (most recent call last):\n!!   File "/usr/lib/python3.6/urllib/request.py", line 1318, in do_open\n    encode_chunked=req.has_header(\'Transfer-encoding\'))\n!!   File "/usr/lib/python3.6/http/client.py", line 1239, in request\n    self._send_request(method, url, body, headers, encode_chunked)\n!!   File "/usr/lib/python3.6/http/client.py", line 1285, in _send_request\n    self.endheaders(body, encode_chunked=encode_chunked)\n!!   File "/usr/lib/python3.6/http/client.py", line 1234, in endheaders\n    self._send_output(message_body, encode_chunked=encode_chunked)\n!!   File "/usr/lib/python3.6/http/client.py", line 1026, in _send_output\n    self.send(msg)\n!!   File "/usr/lib/python3.6/http/client.py", line 964, in send\n    self.connect()\n!!   File "/usr/lib/python3.6/http/client.py", line 1392, in connect\n    super().connect()\n!!   File "/usr/lib/python3.6/http/client.py", line 936, in connect\n    (self.host,self.port), self.timeout, self.source_address)\n!!   File "/usr/lib/python3.6/socket.py", line 704, in create_connection\n    for res in getaddrinfo(host, port, 0, SOCK_STREAM):\n!!   File "/usr/lib/python3.6/socket.py", line 743, in getaddrinfo\n    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):\n!! socket.gaierror: [Errno -2] Name or service not known\n!! \nDuring handling of the above exception, another exception occurred:\n\n!! Traceback (most recent call last):\n!!   File "web_request.py", line 64, in __get_request\n    self.__last_response = urllib.request.urlopen(self.url)\n!!   File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen\n    return opener.open(url, data, timeout)\n!!   File "/usr/lib/python3.6/urllib/request.py", line 526, in open\n    response = self._open(req, data)\n!!   File "/usr/lib/python3.6/urllib/request.py", line 544, in _open\n    \'_open\', req)\n!!   File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain\n    result = func(*args)\n!!   File "/usr/lib/python3.6/urllib/request.py", line 1361, in https_open\n    context=self._context, check_hostname=self._check_hostname)\n!!   File "/usr/lib/python3.6/urllib/request.py", line 1320, in do_open\n    raise URLError(err)\n!! urllib.error.URLError: <urlopen error [Errno -2] Name or service not known>\n'}
CRITICAL:root:{'date': datetime.datetime(2017, 10, 2, 17, 38, 58, 750645), 'type': 'CRITICAL', 'info': 'Error en la url', 'error': '!! Traceback (most recent call last):\n!!   File "/usr/lib/python3.6/urllib/request.py", line 1318, in do_open\n    encode_chunked=req.has_header(\'Transfer-encoding\'))\n!!   File "/usr/lib/python3.6/http/client.py", line 1239, in request\n    self._send_request(method, url, body, headers, encode_chunked)\n!!   File "/usr/lib/python3.6/http/client.py", line 1285, in _send_request\n    self.endheaders(body, encode_chunked=encode_chunked)\n!!   File "/usr/lib/python3.6/http/client.py", line 1234, in endheaders\n    self._send_output(message_body, encode_chunked=encode_chunked)\n!!   File "/usr/lib/python3.6/http/client.py", line 1026, in _send_output\n    self.send(msg)\n!!   File "/usr/lib/python3.6/http/client.py", line 964, in send\n    self.connect()\n!!   File "/usr/lib/python3.6/http/client.py", line 1392, in connect\n    super().connect()\n!!   File "/usr/lib/python3.6/http/client.py", line 936, in connect\n    (self.host,self.port), self.timeout, self.source_address)\n!!   File "/usr/lib/python3.6/socket.py", line 704, in create_connection\n    for res in getaddrinfo(host, port, 0, SOCK_STREAM):\n!!   File "/usr/lib/python3.6/socket.py", line 743, in getaddrinfo\n    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):\n!! socket.gaierror: [Errno -2] Name or service not known\n!! \nDuring handling of the above exception, another exception occurred:\n\n!! Traceback (most recent call last):\n!!   File "web_request.py", line 64, in __get_request\n    self.__last_response = urllib.request.urlopen(self.url)\n!!   File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen\n    return opener.open(url, data, timeout)\n!!   File "/usr/lib/python3.6/urllib/request.py", line 526, in open\n    response = self._open(req, data)\n!!   File "/usr/lib/python3.6/urllib/request.py", line 544, in _open\n    \'_open\', req)\n!!   File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain\n    result = func(*args)\n!!   File "/usr/lib/python3.6/urllib/request.py", line 1361, in https_open\n    context=self._context, check_hostname=self._check_hostname)\n!!   File "/usr/lib/python3.6/urllib/request.py", line 1320, in do_open\n    raise URLError(err)\n!! urllib.error.URLError: <urlopen error [Errno -2] Name or service not known>\n'}
INFO:root:{'date': datetime.datetime(2017, 10, 2, 17, 41, 18, 300424), 'type': 'INFO', 'info': 'http://centraal.academy', 'event': 'url request successfull'}
DEBUG:root:{'date': datetime.datetime(2017, 10, 2, 17, 41, 18, 301193), 'type': 'DEBUG', 'info': 'http://centraal.academy'}
INFO:root:{'date': datetime.datetime(2017, 10, 2, 17, 41, 19, 329860), 'type': 'INFO', 'info': 'http://centraal.academy', 'event': 'url request successfull'}
DEBUG:root:{'date': datetime.datetime(2017, 10, 2, 17, 41, 19, 330390), 'type': 'DEBUG', 'info': 'http://centraal.academy'}
INFO:root:{'date': datetime.datetime(2017, 10, 2, 17, 44, 18, 813175), 'type': 'INFO', 'info': 'http://centraal.academy', 'event': 'url request successfull'}
DEBUG:root:{'date': datetime.datetime(2017, 10, 2, 17, 44, 18, 813781), 'type': 'DEBUG', 'info': 'http://centraal.academy'}
INFO:root:{'date': datetime.datetime(2017, 10, 2, 17, 44, 19, 294185), 'type': 'INFO', 'info': 'http://centraal.academy', 'event': 'url request successfull'}
DEBUG:root:{'date': datetime.datetime(2017, 10, 2, 17, 44, 19, 294900), 'type': 'DEBUG', 'info': 'http://centraal.academy'}
INFO:root:{'date': datetime.datetime(2017, 10, 2, 17, 44, 25, 581479), 'type': 'INFO', 'info': 'http://centraal.academy', 'event': 'url request successfull'}
DEBUG:root:{'date': datetime.datetime(2017, 10, 2, 17, 44, 25, 581941), 'type': 'DEBUG', 'info': 'http://centraal.academy'}
INFO:root:{'date': datetime.datetime(2017, 10, 2, 17, 49, 7, 723876), 'type': 'INFO', 'info': 'https://jsonplaceholder.typicode.com/posts', 'event': 'url request successfull'}
DEBUG:root:{'date': datetime.datetime(2017, 10, 2, 17, 49, 7, 724457), 'type': 'DEBUG', 'info': 'https://jsonplaceholder.typicode.com/posts'}
INFO:root:{'date': datetime.datetime(2017, 10, 2, 17, 49, 8, 101152), 'type': 'INFO', 'info': 'https://jsonplaceholder.typicode.com/posts', 'event': 'url request successfull'}
DEBUG:root:{'date': datetime.datetime(2017, 10, 2, 17, 49, 8, 101664), 'type': 'DEBUG', 'info': 'https://jsonplaceholder.typicode.com/posts'}
INFO:root:{'date': datetime.datetime(2017, 10, 2, 17, 53, 29, 223256), 'type': 'INFO', 'info': 'https://jsonplaceholder.typicode.com/posts', 'event': 'url request successfull'}
DEBUG:root:{'date': datetime.datetime(2017, 10, 2, 17, 53, 29, 223759), 'type': 'DEBUG', 'info': 'https://jsonplaceholder.typicode.com/posts'}
CRITICAL:root:{'date': datetime.datetime(2017, 10, 2, 17, 56, 13, 237692), 'type': 'CRITICAL', 'info': 'Error en la url', 'error': '!! Traceback (most recent call last):\n!!   File "/home/jaciel/CA/scraper/web_request.py", line 87, in __post_request\n    self.__last_response = urllib.request.Request(self.url, self.__request[\'params\'], self.__request[\'headers\'])\n!!   File "/usr/lib/python3.6/urllib/request.py", line 335, in __init__\n    for key, value in headers.items():\n!! AttributeError: \'bytes\' object has no attribute \'items\'\n'}
CRITICAL:root:{'date': datetime.datetime(2017, 10, 2, 18, 24, 34, 188370), 'type': 'CRITICAL', 'info': 'Error en la url', 'error': '!! Traceback (most recent call last):\n!!   File "web_request.py", line 87, in __post_request\n    self.__last_response = urllib.request.Request(self.url, self.__request[\'params\'], self.__request[\'headers\'])\n!!   File "/usr/lib/python3.6/urllib/request.py", line 335, in __init__\n    for key, value in headers.items():\n!! AttributeError: \'str\' object has no attribute \'items\'\n'}
INFO:root:{'date': datetime.datetime(2017, 10, 2, 18, 26, 24, 725354), 'type': 'INFO', 'info': 'https://jsonplaceholder.typicode.com/posts', 'event': 'url request successfull'}
DEBUG:root:{'date': datetime.datetime(2017, 10, 2, 18, 26, 24, 726266), 'type': 'DEBUG', 'info': 'https://jsonplaceholder.typicode.com/posts'}
INFO:root:{'date': datetime.datetime(2017, 10, 2, 18, 26, 30, 890322), 'type': 'INFO', 'info': 'https://jsonplaceholder.typicode.com/posts', 'event': 'url request successfull'}
DEBUG:root:{'date': datetime.datetime(2017, 10, 2, 18, 26, 30, 890850), 'type': 'DEBUG', 'info': 'https://jsonplaceholder.typicode.com/posts'}
CRITICAL:root:{'date': datetime.datetime(2017, 10, 2, 18, 27, 10, 140658), 'type': 'CRITICAL', 'info': 'Error en la url', 'error': '!! Traceback (most recent call last):\n!!   File "/home/jaciel/CA/scraper/web_request.py", line 87, in __post_request\n    self.__last_response = urllib.request.Request(self.url, self.__request[\'params\'], self.__request[\'headers\'])\n!!   File "/usr/lib/python3.6/urllib/request.py", line 335, in __init__\n    for key, value in headers.items():\n!! AttributeError: \'bytes\' object has no attribute \'items\'\n'}
CRITICAL:root:{'date': datetime.datetime(2017, 10, 2, 18, 28, 22, 35159), 'type': 'CRITICAL', 'info': 'Error en la url', 'error': '!! Traceback (most recent call last):\n!!   File "/home/jaciel/CA/scraper/web_request.py", line 87, in __post_request\n    self.__last_response = urllib.request.Request(self.url, self.__request[\'params\'], self.__request[\'headers\'])\n!!   File "/usr/lib/python3.6/urllib/request.py", line 335, in __init__\n    for key, value in headers.items():\n!! AttributeError: \'str\' object has no attribute \'items\'\n'}
CRITICAL:root:{'date': datetime.datetime(2017, 10, 2, 18, 31, 22, 288526), 'type': 'CRITICAL', 'info': 'Error en la url', 'error': '!! Traceback (most recent call last):\n!!   File "web_request.py", line 88, in __post_request\n    self.__last_response = urllib.request.Request(self.url, self.__request[\'params\'], self.__request[\'headers\'])\n!!   File "/usr/lib/python3.6/urllib/request.py", line 335, in __init__\n    for key, value in headers.items():\n!! AttributeError: \'bytes\' object has no attribute \'items\'\n'}
CRITICAL:root:{'date': datetime.datetime(2017, 10, 2, 18, 32, 4, 517132), 'type': 'CRITICAL', 'info': 'Error en la url post', 'error': '!! Traceback (most recent call last):\n!!   File "web_request.py", line 88, in __post_request\n    self.__last_response = urllib.request.Request(self.url, self.__request[\'params\'], self.__request[\'headers\'])\n!!   File "/usr/lib/python3.6/urllib/request.py", line 335, in __init__\n    for key, value in headers.items():\n!! AttributeError: \'bytes\' object has no attribute \'items\'\n'}
CRITICAL:root:{'date': datetime.datetime(2017, 10, 2, 18, 38, 6, 540437), 'type': 'CRITICAL', 'info': 'Error en la url post', 'error': '!! Traceback (most recent call last):\n!!   File "web_request.py", line 88, in __post_request\n    self.__last_response = urllib.request.Request(self.url, self.__request[\'params\'], self.__request[\'headers\'])\n!!   File "/usr/lib/python3.6/urllib/request.py", line 335, in __init__\n    for key, value in headers.items():\n!! AttributeError: \'str\' object has no attribute \'items\'\n'}
CRITICAL:root:{'date': datetime.datetime(2017, 10, 2, 18, 38, 31, 829820), 'type': 'CRITICAL', 'info': 'Error en la url post', 'error': '!! Traceback (most recent call last):\n!!   File "web_request.py", line 88, in __post_request\n    self.__last_response = urllib.request.Request(self.url, self.__request[\'params\'], self.__request[\'headers\'])\n!!   File "/usr/lib/python3.6/urllib/request.py", line 335, in __init__\n    for key, value in headers.items():\n!! AttributeError: \'str\' object has no attribute \'items\'\n'}
CRITICAL:root:{'date': datetime.datetime(2017, 10, 2, 18, 39, 18, 267631), 'type': 'CRITICAL', 'info': 'No se puede procesar el body response', 'error': '!! Traceback (most recent call last):\n!!   File "web_request.py", line 95, in __read_from_request\n    self.response[\'body\'] = self.__last_response.read()\n!! AttributeError: \'Request\' object has no attribute \'read\'\n'}
CRITICAL:root:{'date': datetime.datetime(2017, 10, 2, 18, 39, 56, 638720), 'type': 'CRITICAL', 'info': 'No se puede procesar el body response', 'error': '!! Traceback (most recent call last):\n!!   File "web_request.py", line 95, in __read_from_request\n    self.response[\'body\'] = self.__last_response.read()\n!! AttributeError: \'Request\' object has no attribute \'read\'\n'}
CRITICAL:root:{'date': datetime.datetime(2017, 10, 2, 18, 40, 15, 958470), 'type': 'CRITICAL', 'info': 'No se puede procesar el body response', 'error': '!! Traceback (most recent call last):\n!!   File "web_request.py", line 95, in __read_from_request\n    self.response[\'body\'] = self.__last_response.read()\n!! AttributeError: \'Request\' object has no attribute \'read\'\n'}
INFO:root:{'date': datetime.datetime(2017, 10, 2, 18, 41, 36, 5218), 'type': 'INFO', 'info': 'https://jsonplaceholder.typicode.com/posts', 'event': 'url request successfull'}
DEBUG:root:{'date': datetime.datetime(2017, 10, 2, 18, 41, 36, 5846), 'type': 'DEBUG', 'info': 'https://jsonplaceholder.typicode.com/posts'}
INFO:root:{'date': datetime.datetime(2017, 10, 2, 18, 41, 36, 274668), 'type': 'INFO', 'info': 'https://jsonplaceholder.typicode.com/posts', 'event': 'url request successfull'}
DEBUG:root:{'date': datetime.datetime(2017, 10, 2, 18, 41, 36, 275172), 'type': 'DEBUG', 'info': 'https://jsonplaceholder.typicode.com/posts'}
INFO:root:{'date': datetime.datetime(2017, 10, 2, 18, 41, 45, 2920), 'type': 'INFO', 'info': 'https://jsonplaceholder.typicode.com/posts', 'event': 'url request successfull'}
DEBUG:root:{'date': datetime.datetime(2017, 10, 2, 18, 41, 45, 3486), 'type': 'DEBUG', 'info': 'https://jsonplaceholder.typicode.com/posts'}
INFO:root:{'date': datetime.datetime(2017, 10, 2, 18, 41, 45, 309297), 'type': 'INFO', 'info': 'https://jsonplaceholder.typicode.com/posts', 'event': 'url request successfull'}
DEBUG:root:{'date': datetime.datetime(2017, 10, 2, 18, 41, 45, 310792), 'type': 'DEBUG', 'info': 'https://jsonplaceholder.typicode.com/posts'}
CRITICAL:root:{'date': datetime.datetime(2017, 10, 2, 18, 41, 52, 775598), 'type': 'CRITICAL', 'info': 'No se puede procesar el body response', 'error': '!! Traceback (most recent call last):\n!!   File "web_request.py", line 95, in __read_from_request\n    self.response[\'body\'] = self.__last_response.read()\n!! AttributeError: \'Request\' object has no attribute \'read\'\n'}
INFO:root:{'date': datetime.datetime(2017, 10, 2, 18, 42, 6, 591550), 'type': 'INFO', 'info': 'https://jsonplaceholder.typicode.com/posts', 'event': 'url request successfull'}
DEBUG:root:{'date': datetime.datetime(2017, 10, 2, 18, 42, 6, 596384), 'type': 'DEBUG', 'info': 'https://jsonplaceholder.typicode.com/posts'}
INFO:root:{'date': datetime.datetime(2017, 10, 2, 18, 42, 6, 845589), 'type': 'INFO', 'info': 'https://jsonplaceholder.typicode.com/posts', 'event': 'url request successfull'}
DEBUG:root:{'date': datetime.datetime(2017, 10, 2, 18, 42, 6, 846281), 'type': 'DEBUG', 'info': 'https://jsonplaceholder.typicode.com/posts'}
INFO:root:{'date': datetime.datetime(2017, 10, 2, 18, 42, 19, 786728), 'type': 'INFO', 'info': 'https://jsonplaceholder.typicode.com/posts', 'event': 'url request successfull'}
DEBUG:root:{'date': datetime.datetime(2017, 10, 2, 18, 42, 19, 787287), 'type': 'DEBUG', 'info': 'https://jsonplaceholder.typicode.com/posts'}
INFO:root:{'date': datetime.datetime(2017, 10, 2, 18, 42, 20, 54745), 'type': 'INFO', 'info': 'https://jsonplaceholder.typicode.com/posts', 'event': 'url request successfull'}
DEBUG:root:{'date': datetime.datetime(2017, 10, 2, 18, 42, 20, 55264), 'type': 'DEBUG', 'info': 'https://jsonplaceholder.typicode.com/posts'}
INFO:root:{'date': datetime.datetime(2017, 10, 2, 18, 42, 38, 215741), 'type': 'INFO', 'info': 'https://jsonplaceholder.typicode.com/posts', 'event': 'url request successfull'}
DEBUG:root:{'date': datetime.datetime(2017, 10, 2, 18, 42, 38, 216467), 'type': 'DEBUG', 'info': 'https://jsonplaceholder.typicode.com/posts'}
INFO:root:{'date': datetime.datetime(2017, 10, 2, 18, 42, 38, 497493), 'type': 'INFO', 'info': 'https://jsonplaceholder.typicode.com/posts', 'event': 'url request successfull'}
DEBUG:root:{'date': datetime.datetime(2017, 10, 2, 18, 42, 38, 498192), 'type': 'DEBUG', 'info': 'https://jsonplaceholder.typicode.com/posts'}
INFO:root:{'date': datetime.datetime(2017, 10, 2, 18, 47, 7, 183931), 'type': 'INFO', 'info': 'https://jsonplaceholder.typicode.com/posts', 'event': 'url request successfull'}
DEBUG:root:{'date': datetime.datetime(2017, 10, 2, 18, 47, 7, 184990), 'type': 'DEBUG', 'info': 'https://jsonplaceholder.typicode.com/posts'}
INFO:root:{'date': datetime.datetime(2017, 10, 2, 18, 47, 35, 871540), 'type': 'INFO', 'info': 'https://jsonplaceholder.typicode.com/posts', 'event': 'url request successfull'}
DEBUG:root:{'date': datetime.datetime(2017, 10, 2, 18, 47, 35, 872547), 'type': 'DEBUG', 'info': 'https://jsonplaceholder.typicode.com/posts'}
INFO:root:{'date': datetime.datetime(2017, 10, 2, 18, 48, 20, 820140), 'type': 'INFO', 'info': 'https://jsonplaceholder.typicode.com/posts', 'event': 'url request successfull'}
DEBUG:root:{'date': datetime.datetime(2017, 10, 2, 18, 48, 20, 821224), 'type': 'DEBUG', 'info': 'https://jsonplaceholder.typicode.com/posts'}
INFO:root:{'date': datetime.datetime(2017, 10, 2, 18, 48, 32, 461818), 'type': 'INFO', 'info': 'https://jsonplaceholder.typicode.com/posts', 'event': 'url request successfull'}
DEBUG:root:{'date': datetime.datetime(2017, 10, 2, 18, 48, 32, 462406), 'type': 'DEBUG', 'info': 'https://jsonplaceholder.typicode.com/posts'}
INFO:root:{'date': datetime.datetime(2017, 10, 2, 18, 49, 31, 901386), 'type': 'INFO', 'info': 'https://jsonplaceholder.typicode.com/posts', 'event': 'url request successfull'}
DEBUG:root:{'date': datetime.datetime(2017, 10, 2, 18, 49, 31, 901964), 'type': 'DEBUG', 'info': 'https://jsonplaceholder.typicode.com/posts'}
CRITICAL:root:{'date': datetime.datetime(2017, 10, 2, 18, 49, 31, 903148), 'type': 'CRITICAL', 'info': 'No se puede procesar el body response', 'error': '!! Traceback (most recent call last):\n!!   File "web_request.py", line 104, in __read_from_request\n    self.response[\'body\'] = self.__last_response.read()\n!! AttributeError: \'Request\' object has no attribute \'read\'\n'}
INFO:root:{'date': datetime.datetime(2017, 10, 2, 19, 8, 5, 770623), 'type': 'INFO', 'info': 'https://jsonplaceholder.typicode.com/posts', 'event': 'url request successfull'}
DEBUG:root:{'date': datetime.datetime(2017, 10, 2, 19, 8, 5, 771260), 'type': 'DEBUG', 'info': 'https://jsonplaceholder.typicode.com/posts'}
INFO:root:{'date': datetime.datetime(2017, 10, 2, 19, 8, 6, 10150), 'type': 'INFO', 'info': 'https://jsonplaceholder.typicode.com/posts', 'event': 'url request successfull'}
DEBUG:root:{'date': datetime.datetime(2017, 10, 2, 19, 8, 6, 10821), 'type': 'DEBUG', 'info': 'https://jsonplaceholder.typicode.com/posts'}
